### ISSUE TITLE
Duplicate downloads on wish list

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-wish-lists#40] opened 2015-12-22 14:23 UTC
Originally reported by a customer, I discovered there is an issue with downloads being added to a wish list and being duplicated when viewing the list. However, I've had some difficulty and inconsistency when replicating it. As far as we can tell, the issue only occurs with variable products and so far, only when used with FES and Marketify. Though I can't yet pinpoint the cause, I just can't replicate yet when not using FES and Marketify as well and even then it is inconsistent. I replicated the first time I viewed a wish list but not the second for example. When it does manifest, there's just multiple instances of the same download on the wish list.

I also see this notice which may be related though it shows whether or not the downloads are duplicated:

```
NOTICE: UNDEFINED INDEX: PRICE_ID IN /USERS/KYLEMAURER/DOCUMENTS/WEBSITES/EDD.DEV/WP-CONTENT/PLUGINS/EDD-WISH-LISTS/INCLUDES/TEMPLATE-FUNCTIONS.PHP ON LINE 372
```

**Comment by brashrebel** [comment] 2015-12-23 14:25
Still chasing this bug which was first reported in [this ticket](https://secure.helpscout.net/conversation/150851240/23671/?folderId=448801). So far, seems to manifest only when downloads have variations. Customer site exhibits the issue every time a download with variations is added. My test site does rarely.

**Comment by pippinsplugins** [comment] 2015-12-23 18:01
@sumobi Able to help Kyle track this down?

**Comment by mindctrl** [comment] 2015-12-23 20:58
@brashrebel does the duplication appear in the admin view too or just on the front end?

**Comment by mindctrl** [comment] 2015-12-23 22:14
Also just for reference, an item can be added to a list multiple times. https://github.com/easydigitaldownloads/edd-wish-lists/issues/32

**Comment by sumobi** [comment] 2015-12-23 23:03
Looking soon

**Comment by sumobi** [comment] 2015-12-23 23:55
@brashrebel @pippinsplugins @mindctrl Haven't been able to replicate this yet. Tried importing the customer's submission form from the ticket, thinking it had something to do products submitted via FES. Not seeing any errors or such. Kyle: left you a note on the ticket, I'll login and see if I can spot anything.

**Comment by brashrebel** [comment] 2015-12-24 14:03
The problem only appears on the frontend when viewing a wish list. It occurs every time on the customer site but I was only able to replicate it a couple times and struggled to pinpoint what different factors were in play. This is elusive so far.

**Comment by sumobi** [comment] 2015-12-24 23:06
Looks like the issue was resolved by using their caching plugin to clear the cache. As soon as I cleared the cache only on the customer's site only 1 item was added to the wish list as expected.

@brashrebel I wonder if somehow a combination of Marketify + FES did cause an issue (Marketify makes some custom tweaks to EDD Wish Lists) but since it was cached for the customer, the issue did not go away. I'm guessing you don't have a caching plugin installed locally so the issue resolved itself immediately.

**Comment by spencerfinnell** [comment] 2015-12-25 02:05
Marketify doesn't do much custom stuff with wish lists hear days: https://github.com/Astoundify/marketify/blob/master/inc/integrations/edd-wish-lists/class-edd-wish-lists.php

No templates or anything.

**Comment by sumobi** [comment] 2015-12-27 00:56
@spencerfinnell Good to know. 

@brashrebel Reckon you could try and replicate the issue again with EDD, Wish Lists and FES installed?

**Comment by sumobi** [comment] 2015-12-29 04:55
Finally tracked this down, please bear with me! The issue can be replicated by using:

1. The public version of Wish Lists (v1.1.1)
2. The 2016 theme
3. A variable priced download, either multi check (checkboxes) or normal (radio buttons).
4. EDD's "Download details" widget in the sidebar so it's on the same page

The issue is simply caused by the presence of a 2nd purchase form in the Download Details widget. It can also be replicated with the Marketify theme, since the purchase form is shown within a modal window when you click the purchase button on their "Product Details" widget.

But going back to the 2016 theme for example, if you add option 2 shown in the screenshot below to the wish list, it's also going to add option 1 from the download details widget.

![screen shot 2015-12-29 at 5 13 08 pm](https://cloud.githubusercontent.com/assets/52581/12029423/98684d72-ae4f-11e5-9374-e2977d86f1ef.png)

This can at times make it look like the download option is being duplicated, since it's possible to select both pricing options and click one of the add to wish list buttons.

The good news is that this issue is fixed in the GitHub version of Wish Lists since @mindctrl made this tweak to the JS: https://github.com/easydigitaldownloads/edd-wish-lists/commit/b03901c31869441e189a95de5296c66eb0f0ba30

If you want to test make sure `SCRIPT_DEBUG` is set to `TRUE` since the fix is only in the uncompressed version of the JS script.

The commit essentially changed:

    var form = jQuery('.edd_download_purchase_form');

to:

    var form = $this.closest('.edd_download_purchase_form');

Hooray! since it sets the form variable to be the closest EDD purchase form, it doesn't duplicate any downloads in the wish lists and now works great.

Although the above change is correct, it sadly introduces a new issue on the Marketify theme. On Marketify's "Product Details" widget there are no variable pricing options printed above the purchase button. EDD's "Download Details" widget does show these pricing options above the purchase button.

![screen shot 2015-12-29 at 5 28 56 pm](https://cloud.githubusercontent.com/assets/52581/12029515/ba6db72a-ae51-11e5-8ba3-3f3e0a65c8be.png)

If you now select a variable pricing option from the main download content area and then click "add to wish list" on the widget, you get a JS alert that says "Please select an option". This is essentially what the customer is trying to do since they removed the "add to wishlist" button from the main content area (more on that below).

The pricing options are only shown in a modal window only when you click the purchase button. 

![screen shot 2015-12-29 at 5 29 43 pm](https://cloud.githubusercontent.com/assets/52581/12029520/ca39f2e0-ae51-11e5-8a2f-3b28c5903c65.png)

I don't think the "add to wish list" button actually makes sense here for variable priced downloads (fine for normal downloads), since you need to be able to choose a pricing option first, then add it to the wish list. In it's current state, you would need to click "purchase", select a pricing option, close the modal window, and then finally add it to the wish list. Not very user-friendly at all.

@spencerfinnell Do you agree with that? the simple fix here is to remove the "add to wishlist" button for variable priced downloads, from the "Product Details" widget.

As briefly mentioned earlier, the customer decided they didn't want the "add to wish list" button to be visible within the pricing options in the main download content, so they used a code snippet to remove it. 

___
Before:

![screen shot 2015-12-29 at 5 26 37 pm](https://cloud.githubusercontent.com/assets/52581/12029661/08ac088a-ae55-11e5-81d1-4ce6e8a85072.png)

___

After (with the button removed)

![screen shot 2015-12-29 at 5 53 29 pm](https://cloud.githubusercontent.com/assets/52581/12029664/1978137a-ae55-11e5-9e80-365243d7ca62.png)

___

The customer is now expecting to choose a pricing option from the left hand side's pricing options, and then click the add to wish list button on Marketify's Product details widget. If the download had a lot of content, this would not be a good idea. You would have to scroll to the bottom, select a pricing option, scroll to the top, and then click to add the pricing option to a wish list.

Back to the JS alert. Clicking the add to wish list button in the product details widget causes this alert since it can't see the purchase form within the modal window. I could probably fix this, and tell it to look at the variable pricing options from the main download content, but as per above, it's a bit silly and not very user friendly.

The fix in my eyes is 2 part:

1. Remove the "add to wishlist" button from Marketify's "Product Details" widget, but only for variable priced downloads

2. Tell the customer **not** to remove the "add to wishlist" button from the pricing options that appear in the main download area, for the reason above.

@spencerfinnell @brashrebel @mindctrl would love your thoughts on the above.

**Comment by brashrebel** [comment] 2015-12-29 13:09
Brilliant work @sumobi. I like your suggestions. Though removing the "add to wishlist" button for variable products in that widget with no explanation seems likely to cause confusion, I'm not sure what else to propose. Perhaps that button could be overridden so that clicking it reveals the variations or another modal or something?

**Comment by spencerfinnell** [comment] 2015-12-29 21:20
Hmm... 

I can't really think of a graceful solution. I don't think hiding the "Add to Wishlist" button in the popup is a great solution since most people won't see it. 

This seems like a very rare edge case that is caused by removing the default wish list button which I wouldn't imagine most people would do? If they think their customers will care about saving a specific variation then it shouldn't be removed; otherwise the secondary wish list button in the sidebar will work to save the general download. 

OR:

https://gist.github.com/spencerfinnell/f4a289bd462685e39b4b

Will remove the custom "Buy Now" link (and popup) and output the standard purchase link button (and the CSS will show the variations). A bit extra CSS will be needed for some spacing, etc.

**Comment by sumobi** [comment] 2016-01-02 01:16
@spencerfinnell 

> I can't really think of a graceful solution. I don't think hiding the "Add to Wishlist" button in the popup is a great solution since most people won't see it.

Is there a "Add to wishlist" button in a popup somewhere? I meant the one in the "Product details" widget

> This seems like a very rare edge case that is caused by removing the default wish list button which I wouldn't imagine most people would do? If they think their customers will care about saving a specific variation then it shouldn't be removed; 

Absolutely agree, it should not be removed from the left if the site admin wants their customers to save variations to the wish list.

> otherwise the secondary wish list button in the sidebar will work to save the general download.

Yep

> Will remove the custom "Buy Now" link (and popup) and output the standard purchase link button (and the CSS will show the variations). A bit extra CSS will be needed for some spacing, etc.

Awesome, thanks for that. @brashrebel that's something you could pass on to the customer. You could even tweak it so it only removes the customer buy link and popup for the variable download.

**Comment by sumobi** [comment] 2016-01-02 01:27
@brashrebel Thanks!

I'm going to push out the update today that includes @mindctrl 's patch which will prevent the duplicate downloads. 

> Though removing the "add to wishlist" button for variable products in that widget with no explanation seems likely to cause confusion, I'm not sure what else to propose. Perhaps that button could be overridden so that clicking it reveals the variations or another modal or something?

I don't think it's too confusing. If a customer wants to add a variable priced download to a wish list, use the add to wish list button in the download content area (and don't remove it for variable priced downloads). Either way, something still needs to be done (preferably from Marketify since it's theme-specific) on a variable priced download since the JS error will now appear if the "add to wish list" button is clicked from Marketify's "product details" widget.

**Comment by spencerfinnell** [comment] 2016-01-02 02:01
The patch from @mindctrl will cause the JS error to go away won't it? 

Or I can implement the code I shared above to the theme directly if that will make things easier.

**Comment by sumobi** [comment] 2016-01-02 03:23
@spencerfinnell The patch from @mindctrl fixes the duplicate downloads issue, but will introduce the JS alert, since no options will be selected when you press the "add to wishlist" button in the Marketify widget.

This is because the pricing options for the download are included inside the modal window and the JS can't find the closest purchase form.

Implementing your code directly into the theme would be a good solution if you don't mind.

**Comment by sumobi** [comment] 2016-01-07 00:25
Closing this, v1.1.2 fixed the duplicate downloads being added: https://github.com/easydigitaldownloads/edd-wish-lists/commits/1.1.2

**Closed by sumobi** 2016-01-07 00:25 UTC
